modLoader="javafml"
loaderVersion="[48,)"
issueTrackerURL="https://github.com/3arthqu4ke/pingbypass"
license = "MIT"

[[mods]]
modId = "pingbypass"
version = "${version}"
displayName = "PingBypass"
authors = "3arthqu4ke"
description = "The PingBypass API"

[[dependencies.pingbypass]]
modId="minecraft"
mandatory=true
versionRange="[1.20.4]"
ordering="NONE"
side="CLIENT"